collections:
  working_on:
    output: true
    sort_by: date
    name: What I'm Working On
    description: The Latest Things I'm Working On
    icon: /icons/suitcase.svg
    iconAlt: a suitcase
  My_Tuturiols:
    output: true
    sort_by: date
  My_Blogs:
    output: true
    sort_by: date

collections_dir: my_collections
color-scheme: auto-deafualt-dark
accent-color: 26a69a #hex color value
faded-accent-color: 1d8c81 #hex color value this is used for background when app is launching