collections:
  My_Blogs:
    output: true
    sort_by: date
  My_Tuturiols:
    output: true
    sort_by: date
  What_I_Am_Working_On:
    output: true
    sort_by: date

collections_dir: my_collections
color-scheme: auto-deafualt-dark